import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./header";
import { ContextProvider } from "@/components/ClientComponents";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Task Manager App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <ContextProvider>
          <>
            <Header />
            {children}
          </>
        </ContextProvider>
      </body>
    </html>
  );
}
